Models/UserCredentials.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Shop.Models
{
    public class UserCredentials
    {

        public int id { get; set; }
        [Required]
        [Display(Name = "First and last name")]
        public string Username { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [EmailAddress]
        public string Email { get; set; }

        public string Country { get; set; }
        [Required]
        public string City { get; set; }
        [Required]
        [Display(Name = "Adress")]
        public string Bilding_adress { get; set; }
        public int User_shoping_card { get; set; }



    }
}

Controllers/UserCredentialsController.cs
using Shop.Controllers.service_interaction_classes;
using Shop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Web;
using System.Web.Mvc;

namespace Shop.Controllers
{
    public class UserCredentialsController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(string email, string password)
        {

            Crypt Crypt = new Crypt();
            Login_service service = new Login_service();

            string hashed_password = service.find_hashed_password(email);
            string new_hash = Crypt.Encrypt(password);


            if (hashed_password == new_hash)
            {
                Session["user_email"] = email;
                int id = service.find_user_id(email);
                Session["user_id"] = id;
                


                return RedirectToAction("Index", "Home");
                


            }
            return View();
        }





        public ActionResult Create_user_profile_page()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create_user_profile(UserCredentials _usercredentials, string country)
        {


            services service = new services();
            if (ModelState.IsValid)
            {
                /// {GUID} creating unique ID for newly USER_information column in database and USER shoping cart for each individual user  .
                byte[] newGuid = Guid.NewGuid().ToByteArray();
                int id = BitConverter.ToInt16(newGuid, 0);

                service.create_shoping_cart_for_individual_user(id);
                service.Create_user_in_DB(_usercredentials, country, id);

                Session["successfully"] = "created successfully";
                return Redirect("Login");
            }

            else
            {
                return Redirect("Create_user_profile_page");
            }



        }




        public ActionResult logout() {

            Session["user_email"] = null;

            return RedirectToAction("index","Home");

        }


    }
}

Views/UserCredentials/Create_user_profile_page.cshtml
@model Shop.Models.UserCredentials

@{
    ViewBag.Title = "Create_user_profile_page";
}


<br />


<div class="row">
    <div class="col-lg-8">

        <div class="card" style="width:100%">
            <div class="card-header">
                <h6>Create  account</h6>
            </div>
            <div class="card-body">

                @using (Html.BeginForm("Create_user_profile", "UserCredentials"))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">

                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">

                                <input id="country_selector" name="country" type="text">
                                <input hidden="hidden" id="country_selector" name="country" type="text">



                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Bilding_adress, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Bilding_adress, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Bilding_adress, "", new { @class = "text-danger" })
                            </div>
                        </div>



                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" id="btn" value="Create" class="btn btn-success" />
                            </div>
                        </div>
                    </div>
                }
            </div>
            <div class="card-footer text-muted">

                <div>
                    @Html.ActionLink("back to main page", "Index", "Home")
                </div>
            </div>
        </div>





    </div>
</div>





























Views/UserCredentials/Login.cshtml

@{
    ViewBag.Title = "Login";
}

@{
    if (Session["successfully"] != null)
    {
        <div class="alert alert-success alert-dismissible fade show mt-4" role="alert">
            Profile created succesfully <strong>Thank you !</strong>.
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    };

    Session["successfully"] = null;
}


<div class="row">
    <div class="col-lg-6 pt-5 ">

        <div class="card shadow-lg ">

            <div class="card-header bg-light ">
                <h6 class="text-center"> Enter email adress and password</h6>
            </div>
            @using (Html.BeginForm("Login", "UserCredentials"))
            {
                @Html.AntiForgeryToken()

                <div class="card-body">

                    <form>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Email address :</label>
                            <input name="email" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">

                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Password :</label>
                            <input name="password" type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">

                        </div>
                        <div class="form-group">

                            <label>Dont have account ?</label>
                            <a href="https://localhost:44325/UserCredentials/Create_user_profile_page"><bold>click here</bold></a>
                        </div><br />
                        <button type="submit" class="btn btn-primary">Login</button>
                    </form>


                </div>
            }
        </div>






    </div>
</div>
